# Generated by Django 6.0.1 on 2026-05-02 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiclassification',
            name='confidence',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='report',
            name='priority',
            field=models.CharField(choices=[('low', 'Aşağı'), ('medium', 'Orta'), ('high', 'Yüksək')], default='medium', max_length=20),
        ),
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('pending', 'Gözləmədə'), ('accepted', 'Qəbul edilib'), ('in_progress', 'İcrada'), ('resolved', 'Həll edilib'), ('rejected', 'Rədd edilib')], default='pending', max_length=20),
        ),
    ]
