# Generated by Django 6.0 on 2026-05-02 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_alter_aiclassification_confidence_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='citizen_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
